apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: primary-backup
  namespace: demo
spec:
  task:
    name: pvc-backup
  repository:
    name: minio-repo
  schedule: "*/3 * * * *"
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: datadir-mg7-2
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 999
        runAsGroup: 999