apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg7
  namespace: demo
spec:
  version: "7.0.8"
  deletionPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs1"
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi