apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: minio-repo
  namespace: demo
spec:
  backend:
    s3:
      bucket: backedup
      prefix: stash-backup/mongo
      endpoint: http://minio.minio.svc:9000
      region: us-east-1
    storageSecretName: minio-secret